"""summary_source: honest provenance for the executive summary.

Pure CPU: builds report objects and renders markdown. No LLM, no PDF, no network.
"""

from datetime import datetime
from pathlib import Path

from scpi_control.report_generator.generators.markdown_generator import MarkdownReportGenerator
from scpi_control.report_generator.models.report_data import (
    SUMMARY_SOURCE_AI,
    SUMMARY_SOURCE_COMPUTED,
    SUMMARY_SOURCE_MANUAL,
    ReportMetadata,
    TestReport,
)


def make_report(summary_source):
    report = TestReport(metadata=ReportMetadata(title="Bench", technician="robin", test_date=datetime(2026, 7, 17)))
    report.executive_summary = "A summary."
    report.summary_source = summary_source
    return report


def test_summary_attribution_maps_each_source():
    assert make_report(SUMMARY_SOURCE_AI).summary_attribution() == "Summary generated by AI"
    assert make_report(SUMMARY_SOURCE_COMPUTED).summary_attribution() == "Computed automatically from measurements"
    assert make_report(SUMMARY_SOURCE_MANUAL).summary_attribution() is None


def test_default_summary_source_is_manual():
    report = TestReport(metadata=ReportMetadata(title="Bench", technician="robin", test_date=datetime(2026, 7, 17)))
    assert report.summary_source == SUMMARY_SOURCE_MANUAL
    assert report.summary_attribution() is None


def test_to_dict_carries_summary_source_and_a_derived_back_compat_key():
    d = make_report(SUMMARY_SOURCE_COMPUTED).to_dict()
    assert d["summary_source"] == "computed"
    assert d["ai_generated_summary"] is False  # derived: only True for the AI source
    assert make_report(SUMMARY_SOURCE_AI).to_dict()["ai_generated_summary"] is True


def test_markdown_renders_the_computed_attribution():
    md = MarkdownReportGenerator()._generate_content(make_report(SUMMARY_SOURCE_COMPUTED), Path("."))
    assert "Computed automatically from measurements" in md
    assert "generated by AI" not in md


def test_markdown_renders_the_ai_attribution():
    md = MarkdownReportGenerator()._generate_content(make_report(SUMMARY_SOURCE_AI), Path("."))
    assert "Summary generated by AI" in md


def test_markdown_shows_no_attribution_for_manual():
    md = MarkdownReportGenerator()._generate_content(make_report(SUMMARY_SOURCE_MANUAL), Path("."))
    assert "generated by AI" not in md
    assert "Computed automatically" not in md
